"""
Minimal IFC GUI Viewer for exported PZero IFC files.

Dependencies:
    pip install ifcopenshell pyvista pyvistaqt PySide6

Usage:
    python ifctest.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pyvista as pv
from pyvistaqt import QtInteractor
from PySide6.QtCore import Qt
from PySide6.QtWidgets import (
    QApplication,
    QCheckBox,
    QFileDialog,
    QHBoxLayout,
    QLabel,
    QListWidget,
    QListWidgetItem,
    QMainWindow,
    QMessageBox,
    QPushButton,
    QTextEdit,
    QVBoxLayout,
    QWidget,
)

try:
    import ifcopenshell
    import ifcopenshell.geom
except ImportError:  # pragma: no cover - runtime dependency guard
    ifcopenshell = None


_COLOURS = {
    "IfcBuildingElementProxy": (0.72, 0.72, 0.72, 1.0),
    "IfcWall": (0.78, 0.75, 0.69, 1.0),
    "IfcWallStandardCase": (0.78, 0.75, 0.69, 1.0),
    "IfcSlab": (0.63, 0.63, 0.63, 1.0),
    "IfcRoof": (0.71, 0.39, 0.31, 1.0),
    "IfcColumn": (0.82, 0.78, 0.71, 1.0),
    "IfcBeam": (0.71, 0.63, 0.47, 1.0),
    "IfcWindow": (0.71, 0.86, 0.94, 0.45),
    "IfcDoor": (0.55, 0.39, 0.24, 1.0),
}
_DEFAULT_COLOUR = (0.70, 0.70, 0.70, 1.0)


def _type_colour(ifc_class: str) -> tuple[float, float, float, float]:
    return _COLOURS.get(ifc_class, _DEFAULT_COLOUR)


def load_ifc_blocks(ifc_path: str) -> list[dict]:
    """
    Load IFC geometry as a list of dictionaries containing pyvista meshes and metadata.

    This viewer assumes the IFC geometry generated by IfcOpenShell is already triangulated,
    which is the case for the current PZero IFC export spike.
    """
    if ifcopenshell is None:
        raise RuntimeError("IfcOpenShell is not installed.")

    model = ifcopenshell.open(ifc_path)
    settings = ifcopenshell.geom.settings()
    settings.set(settings.USE_WORLD_COORDS, True)
    settings.set(settings.WELD_VERTICES, True)

    out = []
    for product in model.by_type("IfcProduct"):
        if not getattr(product, "Representation", None):
            continue

        try:
            shape = ifcopenshell.geom.create_shape(settings, product)
        except Exception:
            continue

        verts = np.asarray(shape.geometry.verts, dtype=float).reshape(-1, 3)
        faces = np.asarray(shape.geometry.faces, dtype=np.int32).reshape(-1, 3)
        if verts.size == 0 or faces.size == 0:
            continue

        pv_faces = np.hstack(
            [np.full((len(faces), 1), 3, dtype=np.int32), faces]
        ).ravel()
        mesh = pv.PolyData(verts, pv_faces)

        ifc_class = product.is_a()
        rgba = _type_colour(ifc_class)
        label = getattr(product, "Name", None) or product.GlobalId or ifc_class

        out.append(
            {
                "label": f"{ifc_class} | {label}",
                "global_id": getattr(product, "GlobalId", ""),
                "ifc_class": ifc_class,
                "name": getattr(product, "Name", "") or "",
                "mesh": mesh,
                "color": rgba[:3],
                "opacity": rgba[3],
                "n_points": mesh.n_points,
                "n_cells": mesh.n_cells,
                "bounds": mesh.bounds,
            }
        )

    return out


class IfcViewerWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("IFC Test Viewer")
        self.resize(1400, 900)

        self.items: list[dict] = []
        self.actors = {}
        self.current_path: str | None = None

        central = QWidget()
        self.setCentralWidget(central)
        root = QHBoxLayout(central)

        left_panel = QWidget()
        left_layout = QVBoxLayout(left_panel)
        left_panel.setMaximumWidth(360)

        self.open_btn = QPushButton("Open IFC")
        self.open_btn.clicked.connect(self.open_ifc_dialog)
        left_layout.addWidget(self.open_btn)

        self.edges_chk = QCheckBox("Show Edges")
        self.edges_chk.toggled.connect(self._rerender_scene)
        left_layout.addWidget(self.edges_chk)

        self.status_lbl = QLabel("No IFC loaded.")
        self.status_lbl.setWordWrap(True)
        left_layout.addWidget(self.status_lbl)

        self.object_list = QListWidget()
        self.object_list.currentRowChanged.connect(self._focus_selected_item)
        left_layout.addWidget(self.object_list, 1)

        self.info_box = QTextEdit()
        self.info_box.setReadOnly(True)
        left_layout.addWidget(self.info_box, 1)

        root.addWidget(left_panel)

        self.plotter = QtInteractor(self)
        self.plotter.set_background("white")
        self.plotter.add_axes()
        root.addWidget(self.plotter.interactor, 1)

        if ifcopenshell is None:
            self.status_lbl.setText(
                "IfcOpenShell is not installed. Install it before opening IFC files."
            )

    def open_ifc_dialog(self):
        in_file_name, _ = QFileDialog.getOpenFileName(
            self,
            "Open IFC file",
            "",
            "IFC Files (*.ifc *.ifczip);;All Files (*.*)",
        )
        if in_file_name:
            self.load_file(in_file_name)

    def load_file(self, ifc_path: str):
        try:
            self.items = load_ifc_blocks(ifc_path)
        except Exception as exc:
            QMessageBox.critical(self, "IFC Load Error", str(exc))
            return

        self.current_path = ifc_path
        self._populate_ui()
        self._rerender_scene()

    def _populate_ui(self):
        self.object_list.clear()
        self.info_box.clear()

        if not self.items:
            self.status_lbl.setText("No renderable IFC geometry found.")
            return

        total_points = sum(item["n_points"] for item in self.items)
        total_cells = sum(item["n_cells"] for item in self.items)
        self.status_lbl.setText(
            f"{Path(self.current_path).name}\n"
            f"Objects: {len(self.items)} | Points: {total_points} | Triangles: {total_cells}"
        )

        for item in self.items:
            widget_item = QListWidgetItem(item["label"])
            widget_item.setData(Qt.UserRole, item)
            self.object_list.addItem(widget_item)

        self.object_list.setCurrentRow(0)

    def _rerender_scene(self):
        self.plotter.clear()
        self.plotter.set_background("white")
        self.plotter.add_axes()
        self.actors.clear()

        show_edges = self.edges_chk.isChecked()
        for index, item in enumerate(self.items):
            actor = self.plotter.add_mesh(
                item["mesh"],
                color=item["color"],
                opacity=item["opacity"],
                show_edges=show_edges,
                edge_color="black",
                line_width=1,
                smooth_shading=False,
                name=f"mesh_{index}",
            )
            self.actors[index] = actor

        if self.items:
            self.plotter.reset_camera()
            self._focus_selected_item(self.object_list.currentRow())
        else:
            self.info_box.setText("Load an IFC file to inspect its geometry.")

    def _focus_selected_item(self, row: int):
        if row < 0 or row >= len(self.items):
            return

        item = self.items[row]
        self.info_box.setText(self._format_item_info(item))

        actor = self.actors.get(row)
        if actor is None:
            return

        self.plotter.reset_camera(bounds=item["bounds"])
        self.plotter.render()

    @staticmethod
    def _format_item_info(item: dict) -> str:
        xmin, xmax, ymin, ymax, zmin, zmax = item["bounds"]
        return (
            f"Class: {item['ifc_class']}\n"
            f"Name: {item['name'] or 'n/a'}\n"
            f"GlobalId: {item['global_id'] or 'n/a'}\n"
            f"Points: {item['n_points']}\n"
            f"Triangles: {item['n_cells']}\n"
            f"Bounds:\n"
            f"  X: {xmin:.3f} .. {xmax:.3f}\n"
            f"  Y: {ymin:.3f} .. {ymax:.3f}\n"
            f"  Z: {zmin:.3f} .. {zmax:.3f}"
        )


def main():
    app = QApplication.instance() or QApplication(sys.argv)
    window = IfcViewerWindow()
    window.show()
    sys.exit(app.exec())


if __name__ == "__main__":
    main()
