# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'base_view_windowYebcpO.ui'
##
## Created by: Qt User Interface Compiler version 6.7.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QFrame, QHBoxLayout,
    QHeaderView, QLayout, QMainWindow, QMenu,
    QMenuBar, QSizePolicy, QSplitter, QStatusBar,
    QTableWidget, QTableWidgetItem, QToolBar, QToolBox,
    QTreeWidget, QTreeWidgetItem, QVBoxLayout, QWidget)

class Ui_BaseViewWindow(object):
    def setupUi(self, BaseViewWindow):
        if not BaseViewWindow.objectName():
            BaseViewWindow.setObjectName(u"BaseViewWindow")
        BaseViewWindow.resize(1280, 800)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(BaseViewWindow.sizePolicy().hasHeightForWidth())
        BaseViewWindow.setSizePolicy(sizePolicy)
        BaseViewWindow.setMinimumSize(QSize(1280, 800))
        BaseViewWindow.setBaseSize(QSize(0, 30))
        BaseViewWindow.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.actionClose = QAction(BaseViewWindow)
        self.actionClose.setObjectName(u"actionClose")
        self.actionBase_Tool = QAction(BaseViewWindow)
        self.actionBase_Tool.setObjectName(u"actionBase_Tool")
        self.actionFilters = QAction(BaseViewWindow)
        self.actionFilters.setObjectName(u"actionFilters")
        font = QFont()
        font.setBold(True)
        font.setItalic(True)
        self.actionFilters.setFont(font)
        self.actionSurface_densityf = QAction(BaseViewWindow)
        self.actionSurface_densityf.setObjectName(u"actionSurface_densityf")
        self.actionRoughnessf = QAction(BaseViewWindow)
        self.actionRoughnessf.setObjectName(u"actionRoughnessf")
        self.actionCurvaturef = QAction(BaseViewWindow)
        self.actionCurvaturef.setObjectName(u"actionCurvaturef")
        self.actionNormalsf = QAction(BaseViewWindow)
        self.actionNormalsf.setObjectName(u"actionNormalsf")
        font1 = QFont()
        font1.setBold(True)
        font1.setItalic(True)
        font1.setUnderline(False)
        self.actionNormalsf.setFont(font1)
        self.actionCalculate_normals = QAction(BaseViewWindow)
        self.actionCalculate_normals.setObjectName(u"actionCalculate_normals")
        self.actionNormals_to_DDR = QAction(BaseViewWindow)
        self.actionNormals_to_DDR.setObjectName(u"actionNormals_to_DDR")
        self.actionPickers = QAction(BaseViewWindow)
        self.actionPickers.setObjectName(u"actionPickers")
        self.actionPickers.setFont(font)
        self.actionManual_picking = QAction(BaseViewWindow)
        self.actionManual_picking.setObjectName(u"actionManual_picking")
        self.actionThresholdf = QAction(BaseViewWindow)
        self.actionThresholdf.setObjectName(u"actionThresholdf")
        self.actionSegment = QAction(BaseViewWindow)
        self.actionSegment.setObjectName(u"actionSegment")
        self.actionPick = QAction(BaseViewWindow)
        self.actionPick.setObjectName(u"actionPick")
        self.actionFacets = QAction(BaseViewWindow)
        self.actionFacets.setObjectName(u"actionFacets")
        self.actionCalibration = QAction(BaseViewWindow)
        self.actionCalibration.setObjectName(u"actionCalibration")
        self.actionManualInner = QAction(BaseViewWindow)
        self.actionManualInner.setObjectName(u"actionManualInner")
        self.actionManualOuter = QAction(BaseViewWindow)
        self.actionManualOuter.setObjectName(u"actionManualOuter")
        self.actionManualBoth = QAction(BaseViewWindow)
        self.actionManualBoth.setObjectName(u"actionManualBoth")
        self.centralwidget = QWidget(BaseViewWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QSize(1280, 726))
        self.centralwidget.setBaseSize(QSize(1280, 726))
        self.verticalLayout_2 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.splitter = QSplitter(self.centralwidget)
        self.splitter.setObjectName(u"splitter")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(1)
        sizePolicy1.setVerticalStretch(1)
        sizePolicy1.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy1)
        self.splitter.setMinimumSize(QSize(0, 0))
        self.splitter.setBaseSize(QSize(0, 0))
        self.splitter.setLineWidth(0)
        self.splitter.setOrientation(Qt.Orientation.Horizontal)
        self.toolBox = QToolBox(self.splitter)
        self.toolBox.setObjectName(u"toolBox")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy2)
        self.toolBox.setMinimumSize(QSize(0, 0))
        self.toolBox.setBaseSize(QSize(0, 0))
        self.toolBox.setFrameShadow(QFrame.Shadow.Raised)
        self.GeologyTreePage = QWidget()
        self.GeologyTreePage.setObjectName(u"GeologyTreePage")
        self.GeologyTreePage.setGeometry(QRect(0, 0, 274, 348))
        sizePolicy1.setHeightForWidth(self.GeologyTreePage.sizePolicy().hasHeightForWidth())
        self.GeologyTreePage.setSizePolicy(sizePolicy1)
        self.GeologyTreePage.setMinimumSize(QSize(0, 0))
        self.GeologyTreePage.setBaseSize(QSize(0, 0))
        self.verticalLayout_7 = QVBoxLayout(self.GeologyTreePage)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.GeologyTreeWidget = QTreeWidget(self.GeologyTreePage)
        __qtreewidgetitem = QTreeWidgetItem()
        __qtreewidgetitem.setText(0, u"1");
        self.GeologyTreeWidget.setHeaderItem(__qtreewidgetitem)
        self.GeologyTreeWidget.setObjectName(u"GeologyTreeWidget")
        sizePolicy1.setHeightForWidth(self.GeologyTreeWidget.sizePolicy().hasHeightForWidth())
        self.GeologyTreeWidget.setSizePolicy(sizePolicy1)
        self.GeologyTreeWidget.setMinimumSize(QSize(0, 0))
        self.GeologyTreeWidget.setMaximumSize(QSize(16777215, 16777215))
        self.GeologyTreeWidget.setBaseSize(QSize(0, 0))

        self.verticalLayout_7.addWidget(self.GeologyTreeWidget)

        self.toolBox.addItem(self.GeologyTreePage, u"Geology > Geology Tree")
        self.TopologyTreePage = QWidget()
        self.TopologyTreePage.setObjectName(u"TopologyTreePage")
        self.TopologyTreePage.setGeometry(QRect(0, 0, 98, 74))
        sizePolicy1.setHeightForWidth(self.TopologyTreePage.sizePolicy().hasHeightForWidth())
        self.TopologyTreePage.setSizePolicy(sizePolicy1)
        self.TopologyTreePage.setMinimumSize(QSize(0, 0))
        self.TopologyTreePage.setBaseSize(QSize(0, 0))
        self.verticalLayout_6 = QVBoxLayout(self.TopologyTreePage)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.TopologyTreeWidget = QTreeWidget(self.TopologyTreePage)
        __qtreewidgetitem1 = QTreeWidgetItem()
        __qtreewidgetitem1.setText(0, u"1");
        self.TopologyTreeWidget.setHeaderItem(__qtreewidgetitem1)
        self.TopologyTreeWidget.setObjectName(u"TopologyTreeWidget")
        sizePolicy1.setHeightForWidth(self.TopologyTreeWidget.sizePolicy().hasHeightForWidth())
        self.TopologyTreeWidget.setSizePolicy(sizePolicy1)
        self.TopologyTreeWidget.setMinimumSize(QSize(0, 0))
        self.TopologyTreeWidget.setBaseSize(QSize(0, 0))

        self.verticalLayout_6.addWidget(self.TopologyTreeWidget)

        self.toolBox.addItem(self.TopologyTreePage, u"Geology > Topology Tree")
        self.XSectionListPage = QWidget()
        self.XSectionListPage.setObjectName(u"XSectionListPage")
        self.XSectionListPage.setGeometry(QRect(0, 0, 98, 74))
        sizePolicy1.setHeightForWidth(self.XSectionListPage.sizePolicy().hasHeightForWidth())
        self.XSectionListPage.setSizePolicy(sizePolicy1)
        self.XSectionListPage.setMinimumSize(QSize(0, 0))
        self.XSectionListPage.setBaseSize(QSize(0, 0))
        self.verticalLayout_5 = QVBoxLayout(self.XSectionListPage)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.XSectionTreeWidget = QTreeWidget(self.XSectionListPage)
        __qtreewidgetitem2 = QTreeWidgetItem()
        __qtreewidgetitem2.setText(0, u"1");
        self.XSectionTreeWidget.setHeaderItem(__qtreewidgetitem2)
        self.XSectionTreeWidget.setObjectName(u"XSectionTreeWidget")
        sizePolicy1.setHeightForWidth(self.XSectionTreeWidget.sizePolicy().hasHeightForWidth())
        self.XSectionTreeWidget.setSizePolicy(sizePolicy1)
        self.XSectionTreeWidget.setMinimumSize(QSize(0, 0))
        self.XSectionTreeWidget.setBaseSize(QSize(0, 0))
        self.XSectionTreeWidget.setTabKeyNavigation(True)
        self.XSectionTreeWidget.setDragDropOverwriteMode(True)
        self.XSectionTreeWidget.setSelectionMode(QAbstractItemView.SelectionMode.ExtendedSelection)
        self.XSectionTreeWidget.setHorizontalScrollMode(QAbstractItemView.ScrollMode.ScrollPerItem)
        self.XSectionTreeWidget.setAutoExpandDelay(-1)

        self.verticalLayout_5.addWidget(self.XSectionTreeWidget)

        self.toolBox.addItem(self.XSectionListPage, u"X Section")
        self.BoundariesPage = QWidget()
        self.BoundariesPage.setObjectName(u"BoundariesPage")
        self.BoundariesPage.setGeometry(QRect(0, 0, 98, 74))
        sizePolicy2.setHeightForWidth(self.BoundariesPage.sizePolicy().hasHeightForWidth())
        self.BoundariesPage.setSizePolicy(sizePolicy2)
        self.verticalLayout_8 = QVBoxLayout(self.BoundariesPage)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.BoundariesTableWidget = QTableWidget(self.BoundariesPage)
        self.BoundariesTableWidget.setObjectName(u"BoundariesTableWidget")
        sizePolicy1.setHeightForWidth(self.BoundariesTableWidget.sizePolicy().hasHeightForWidth())
        self.BoundariesTableWidget.setSizePolicy(sizePolicy1)
        self.BoundariesTableWidget.setMinimumSize(QSize(0, 0))
        self.BoundariesTableWidget.setBaseSize(QSize(0, 0))

        self.verticalLayout_8.addWidget(self.BoundariesTableWidget)

        self.toolBox.addItem(self.BoundariesPage, u"Boundaries")
        self.Mesh3DPage = QWidget()
        self.Mesh3DPage.setObjectName(u"Mesh3DPage")
        self.Mesh3DPage.setGeometry(QRect(0, 0, 98, 74))
        sizePolicy1.setHeightForWidth(self.Mesh3DPage.sizePolicy().hasHeightForWidth())
        self.Mesh3DPage.setSizePolicy(sizePolicy1)
        self.Mesh3DPage.setMinimumSize(QSize(0, 0))
        self.Mesh3DPage.setBaseSize(QSize(0, 0))
        self.verticalLayout_4 = QVBoxLayout(self.Mesh3DPage)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.Mesh3DTableWidget = QTableWidget(self.Mesh3DPage)
        self.Mesh3DTableWidget.setObjectName(u"Mesh3DTableWidget")
        sizePolicy1.setHeightForWidth(self.Mesh3DTableWidget.sizePolicy().hasHeightForWidth())
        self.Mesh3DTableWidget.setSizePolicy(sizePolicy1)
        self.Mesh3DTableWidget.setMinimumSize(QSize(0, 0))
        self.Mesh3DTableWidget.setBaseSize(QSize(0, 0))

        self.verticalLayout_4.addWidget(self.Mesh3DTableWidget)

        self.toolBox.addItem(self.Mesh3DPage, u"3D Meshes and Grids")
        self.DOMsPage = QWidget()
        self.DOMsPage.setObjectName(u"DOMsPage")
        self.DOMsPage.setGeometry(QRect(0, 0, 98, 74))
        sizePolicy1.setHeightForWidth(self.DOMsPage.sizePolicy().hasHeightForWidth())
        self.DOMsPage.setSizePolicy(sizePolicy1)
        self.DOMsPage.setMinimumSize(QSize(0, 0))
        self.DOMsPage.setBaseSize(QSize(0, 0))
        self.verticalLayout_3 = QVBoxLayout(self.DOMsPage)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.DOMsTableWidget = QTableWidget(self.DOMsPage)
        self.DOMsTableWidget.setObjectName(u"DOMsTableWidget")
        sizePolicy1.setHeightForWidth(self.DOMsTableWidget.sizePolicy().hasHeightForWidth())
        self.DOMsTableWidget.setSizePolicy(sizePolicy1)
        self.DOMsTableWidget.setMinimumSize(QSize(0, 0))
        self.DOMsTableWidget.setBaseSize(QSize(0, 0))

        self.verticalLayout_3.addWidget(self.DOMsTableWidget)

        self.toolBox.addItem(self.DOMsPage, u"DEMs and DOMs")
        self.WellsPage = QWidget()
        self.WellsPage.setObjectName(u"WellsPage")
        self.WellsPage.setGeometry(QRect(0, 0, 98, 74))
        self.verticalLayout_9 = QVBoxLayout(self.WellsPage)
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.WellsTreeWidget = QTreeWidget(self.WellsPage)
        __qtreewidgetitem3 = QTreeWidgetItem()
        __qtreewidgetitem3.setText(0, u"1");
        self.WellsTreeWidget.setHeaderItem(__qtreewidgetitem3)
        self.WellsTreeWidget.setObjectName(u"WellsTreeWidget")

        self.verticalLayout_9.addWidget(self.WellsTreeWidget)

        self.toolBox.addItem(self.WellsPage, u"Wells")
        self.FluidsTreePage = QWidget()
        self.FluidsTreePage.setObjectName(u"FluidsTreePage")
        self.FluidsTreePage.setGeometry(QRect(0, 0, 98, 74))
        self.verticalLayout_10 = QVBoxLayout(self.FluidsTreePage)
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.FluidsTreeWidget = QTreeWidget(self.FluidsTreePage)
        __qtreewidgetitem4 = QTreeWidgetItem()
        __qtreewidgetitem4.setText(0, u"1");
        self.FluidsTreeWidget.setHeaderItem(__qtreewidgetitem4)
        self.FluidsTreeWidget.setObjectName(u"FluidsTreeWidget")

        self.verticalLayout_10.addWidget(self.FluidsTreeWidget)

        self.toolBox.addItem(self.FluidsTreePage, u"Fluids > Fluids Tree")
        self.FluidsTopologyTree = QWidget()
        self.FluidsTopologyTree.setObjectName(u"FluidsTopologyTree")
        self.FluidsTopologyTree.setGeometry(QRect(0, 0, 98, 74))
        self.verticalLayout_11 = QVBoxLayout(self.FluidsTopologyTree)
        self.verticalLayout_11.setObjectName(u"verticalLayout_11")
        self.FluidsTopologyTreeWidget = QTreeWidget(self.FluidsTopologyTree)
        __qtreewidgetitem5 = QTreeWidgetItem()
        __qtreewidgetitem5.setText(0, u"1");
        self.FluidsTopologyTreeWidget.setHeaderItem(__qtreewidgetitem5)
        self.FluidsTopologyTreeWidget.setObjectName(u"FluidsTopologyTreeWidget")

        self.verticalLayout_11.addWidget(self.FluidsTopologyTreeWidget)

        self.toolBox.addItem(self.FluidsTopologyTree, u"Fluids > Topology Tree")
        self.BackgroundsTreePage = QWidget()
        self.BackgroundsTreePage.setObjectName(u"BackgroundsTreePage")
        self.BackgroundsTreePage.setGeometry(QRect(0, 0, 98, 74))
        self.verticalLayout_12 = QVBoxLayout(self.BackgroundsTreePage)
        self.verticalLayout_12.setObjectName(u"verticalLayout_12")
        self.BackgroundsTreeWidget = QTreeWidget(self.BackgroundsTreePage)
        __qtreewidgetitem6 = QTreeWidgetItem()
        __qtreewidgetitem6.setText(0, u"1");
        self.BackgroundsTreeWidget.setHeaderItem(__qtreewidgetitem6)
        self.BackgroundsTreeWidget.setObjectName(u"BackgroundsTreeWidget")

        self.verticalLayout_12.addWidget(self.BackgroundsTreeWidget)

        self.toolBox.addItem(self.BackgroundsTreePage, u"Background data > Backgrounds tree")
        self.BackgroundsTopologyTree = QWidget()
        self.BackgroundsTopologyTree.setObjectName(u"BackgroundsTopologyTree")
        self.BackgroundsTopologyTree.setGeometry(QRect(0, 0, 98, 74))
        self.verticalLayout_13 = QVBoxLayout(self.BackgroundsTopologyTree)
        self.verticalLayout_13.setObjectName(u"verticalLayout_13")
        self.BackgroundsTopologyTreeWidget = QTreeWidget(self.BackgroundsTopologyTree)
        __qtreewidgetitem7 = QTreeWidgetItem()
        __qtreewidgetitem7.setText(0, u"1");
        self.BackgroundsTopologyTreeWidget.setHeaderItem(__qtreewidgetitem7)
        self.BackgroundsTopologyTreeWidget.setObjectName(u"BackgroundsTopologyTreeWidget")

        self.verticalLayout_13.addWidget(self.BackgroundsTopologyTreeWidget)

        self.toolBox.addItem(self.BackgroundsTopologyTree, u"Background data > Topology tree")
        self.ImagesPage = QWidget()
        self.ImagesPage.setObjectName(u"ImagesPage")
        self.ImagesPage.setGeometry(QRect(0, 0, 98, 74))
        sizePolicy1.setHeightForWidth(self.ImagesPage.sizePolicy().hasHeightForWidth())
        self.ImagesPage.setSizePolicy(sizePolicy1)
        self.ImagesPage.setMinimumSize(QSize(0, 0))
        self.ImagesPage.setBaseSize(QSize(0, 0))
        self.verticalLayout = QVBoxLayout(self.ImagesPage)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.ImagesTableWidget = QTableWidget(self.ImagesPage)
        self.ImagesTableWidget.setObjectName(u"ImagesTableWidget")
        sizePolicy1.setHeightForWidth(self.ImagesTableWidget.sizePolicy().hasHeightForWidth())
        self.ImagesTableWidget.setSizePolicy(sizePolicy1)
        self.ImagesTableWidget.setMinimumSize(QSize(0, 0))
        self.ImagesTableWidget.setBaseSize(QSize(0, 0))

        self.verticalLayout.addWidget(self.ImagesTableWidget)

        self.toolBox.addItem(self.ImagesPage, u"Images")
        self.splitter.addWidget(self.toolBox)
        self.ViewFrame = QFrame(self.splitter)
        self.ViewFrame.setObjectName(u"ViewFrame")
        self.ViewFrame.setEnabled(True)
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy3.setHorizontalStretch(1)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.ViewFrame.sizePolicy().hasHeightForWidth())
        self.ViewFrame.setSizePolicy(sizePolicy3)
        self.ViewFrame.setMinimumSize(QSize(0, 0))
        self.ViewFrame.setBaseSize(QSize(0, 0))
        self.ViewFrame.setFrameShape(QFrame.Shape.NoFrame)
        self.ViewFrame.setFrameShadow(QFrame.Shadow.Plain)
        self.ViewFrame.setLineWidth(0)
        self.horizontalLayout = QHBoxLayout(self.ViewFrame)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.ViewFrameLayout = QVBoxLayout()
        self.ViewFrameLayout.setSpacing(8)
        self.ViewFrameLayout.setObjectName(u"ViewFrameLayout")
        self.ViewFrameLayout.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.ViewFrameLayout.setContentsMargins(4, 4, 4, 4)

        self.horizontalLayout.addLayout(self.ViewFrameLayout)

        self.splitter.addWidget(self.ViewFrame)

        self.verticalLayout_2.addWidget(self.splitter)

        BaseViewWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(BaseViewWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1280, 33))
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Fixed)
        sizePolicy4.setHorizontalStretch(1)
        sizePolicy4.setVerticalStretch(1)
        sizePolicy4.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy4)
        self.menubar.setMinimumSize(QSize(1280, 30))
        self.menubar.setBaseSize(QSize(1280, 18))
        font2 = QFont()
        font2.setFamilies([u"MS Shell Dlg 2"])
        font2.setPointSize(8)
        font2.setBold(True)
        self.menubar.setFont(font2)
        self.menuBaseView = QMenu(self.menubar)
        self.menuBaseView.setObjectName(u"menuBaseView")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuWindow = QMenu(self.menubar)
        self.menuWindow.setObjectName(u"menuWindow")
        self.menuTools = QMenu(self.menubar)
        self.menuTools.setObjectName(u"menuTools")
        self.menuAutomatic_segmentation = QMenu(self.menuTools)
        self.menuAutomatic_segmentation.setObjectName(u"menuAutomatic_segmentation")
        self.menuManual = QMenu(self.menuTools)
        self.menuManual.setObjectName(u"menuManual")
        BaseViewWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(BaseViewWindow)
        self.statusbar.setObjectName(u"statusbar")
        sizePolicy4.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy4)
        self.statusbar.setMinimumSize(QSize(1280, 18))
        self.statusbar.setBaseSize(QSize(1280, 18))
        BaseViewWindow.setStatusBar(self.statusbar)
        self.toolBarBase = QToolBar(BaseViewWindow)
        self.toolBarBase.setObjectName(u"toolBarBase")
        sizePolicy4.setHeightForWidth(self.toolBarBase.sizePolicy().hasHeightForWidth())
        self.toolBarBase.setSizePolicy(sizePolicy4)
        self.toolBarBase.setMinimumSize(QSize(1280, 30))
        self.toolBarBase.setBaseSize(QSize(1280, 30))
        BaseViewWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBarBase)

        self.menubar.addAction(self.menuBaseView.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuWindow.addAction(self.actionClose)
        self.menuTools.addAction(self.actionFilters)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionSurface_densityf)
        self.menuTools.addAction(self.actionRoughnessf)
        self.menuTools.addAction(self.actionCurvaturef)
        self.menuTools.addAction(self.actionThresholdf)
        self.menuTools.addAction(self.menuManual.menuAction())
        self.menuTools.addAction(self.actionNormalsf)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionCalculate_normals)
        self.menuTools.addAction(self.actionNormals_to_DDR)
        self.menuTools.addAction(self.actionPickers)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionCalibration)
        self.menuTools.addAction(self.actionManual_picking)
        self.menuTools.addAction(self.menuAutomatic_segmentation.menuAction())
        self.menuAutomatic_segmentation.addAction(self.actionSegment)
        self.menuAutomatic_segmentation.addAction(self.actionPick)
        self.menuAutomatic_segmentation.addAction(self.actionFacets)
        self.menuManual.addAction(self.actionManualInner)
        self.menuManual.addAction(self.actionManualOuter)
        self.menuManual.addAction(self.actionManualBoth)

        self.retranslateUi(BaseViewWindow)

        self.toolBox.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(BaseViewWindow)
    # setupUi

    def retranslateUi(self, BaseViewWindow):
        BaseViewWindow.setWindowTitle(QCoreApplication.translate("BaseViewWindow", u"Base View", None))
        self.actionClose.setText(QCoreApplication.translate("BaseViewWindow", u"Close Window", None))
        self.actionBase_Tool.setText(QCoreApplication.translate("BaseViewWindow", u"Base Tool", None))
        self.actionFilters.setText(QCoreApplication.translate("BaseViewWindow", u"Filters", None))
        self.actionSurface_densityf.setText(QCoreApplication.translate("BaseViewWindow", u"Surface density", None))
        self.actionRoughnessf.setText(QCoreApplication.translate("BaseViewWindow", u"Roughness", None))
        self.actionCurvaturef.setText(QCoreApplication.translate("BaseViewWindow", u"Curvature", None))
        self.actionNormalsf.setText(QCoreApplication.translate("BaseViewWindow", u"Normals", None))
        self.actionCalculate_normals.setText(QCoreApplication.translate("BaseViewWindow", u"Calculate normals", None))
        self.actionNormals_to_DDR.setText(QCoreApplication.translate("BaseViewWindow", u"Normals to Dip/Dip direction", None))
        self.actionPickers.setText(QCoreApplication.translate("BaseViewWindow", u"Pickers", None))
        self.actionManual_picking.setText(QCoreApplication.translate("BaseViewWindow", u"Manual picking", None))
        self.actionThresholdf.setText(QCoreApplication.translate("BaseViewWindow", u"Threshold", None))
        self.actionSegment.setText(QCoreApplication.translate("BaseViewWindow", u"Segment", None))
        self.actionPick.setText(QCoreApplication.translate("BaseViewWindow", u"Pick", None))
        self.actionFacets.setText(QCoreApplication.translate("BaseViewWindow", u"Facets", None))
        self.actionCalibration.setText(QCoreApplication.translate("BaseViewWindow", u"Calibration", None))
        self.actionManualInner.setText(QCoreApplication.translate("BaseViewWindow", u"Inner", None))
        self.actionManualOuter.setText(QCoreApplication.translate("BaseViewWindow", u"Outer", None))
        self.actionManualBoth.setText(QCoreApplication.translate("BaseViewWindow", u"Both", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.GeologyTreePage), QCoreApplication.translate("BaseViewWindow", u"Geology > Geology Tree", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.TopologyTreePage), QCoreApplication.translate("BaseViewWindow", u"Geology > Topology Tree", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.XSectionListPage), QCoreApplication.translate("BaseViewWindow", u"X Section", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.BoundariesPage), QCoreApplication.translate("BaseViewWindow", u"Boundaries", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Mesh3DPage), QCoreApplication.translate("BaseViewWindow", u"3D Meshes and Grids", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.DOMsPage), QCoreApplication.translate("BaseViewWindow", u"DEMs and DOMs", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.WellsPage), QCoreApplication.translate("BaseViewWindow", u"Wells", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.FluidsTreePage), QCoreApplication.translate("BaseViewWindow", u"Fluids > Fluids Tree", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.FluidsTopologyTree), QCoreApplication.translate("BaseViewWindow", u"Fluids > Topology Tree", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.BackgroundsTreePage), QCoreApplication.translate("BaseViewWindow", u"Background data > Backgrounds tree", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.BackgroundsTopologyTree), QCoreApplication.translate("BaseViewWindow", u"Background data > Topology tree", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.ImagesPage), QCoreApplication.translate("BaseViewWindow", u"Images", None))
        self.menuBaseView.setTitle(QCoreApplication.translate("BaseViewWindow", u"Base View", None))
        self.menuHelp.setTitle(QCoreApplication.translate("BaseViewWindow", u"Help", None))
        self.menuWindow.setTitle(QCoreApplication.translate("BaseViewWindow", u"Window", None))
        self.menuTools.setTitle(QCoreApplication.translate("BaseViewWindow", u"Tools", None))
        self.menuAutomatic_segmentation.setTitle(QCoreApplication.translate("BaseViewWindow", u"Automatic segmentation", None))
        self.menuManual.setTitle(QCoreApplication.translate("BaseViewWindow", u"Manual", None))
        self.toolBarBase.setWindowTitle(QCoreApplication.translate("BaseViewWindow", u"toolBar", None))
    # retranslateUi

