# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'navigator_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NavWindow(object):
    def setupUi(self, NavWindow):
        NavWindow.setObjectName("NavWindow")
        NavWindow.resize(540, 95)
        NavWindow.setMinimumSize(QtCore.QSize(540, 90))
        NavWindow.setMaximumSize(QtCore.QSize(562, 95))
        self.centralwidget = QtWidgets.QWidget(NavWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.NavGrid = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NavGrid.sizePolicy().hasHeightForWidth())
        self.NavGrid.setSizePolicy(sizePolicy)
        self.NavGrid.setMinimumSize(QtCore.QSize(540, 45))
        self.NavGrid.setMaximumSize(QtCore.QSize(815, 65))
        self.NavGrid.setObjectName("NavGrid")
        self.gridLayout = QtWidgets.QGridLayout(self.NavGrid)
        self.gridLayout.setObjectName("gridLayout")
        self.ForwardButton = QtWidgets.QPushButton(self.NavGrid)
        self.ForwardButton.setObjectName("ForwardButton")
        self.gridLayout.addWidget(self.ForwardButton, 0, 2, 1, 1)
        self.BackButton = QtWidgets.QPushButton(self.NavGrid)
        self.BackButton.setObjectName("BackButton")
        self.gridLayout.addWidget(self.BackButton, 0, 0, 1, 1)
        self.SectionLabel = QtWidgets.QLabel(self.NavGrid)
        self.SectionLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SectionLabel.setText("")
        self.SectionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SectionLabel.setObjectName("SectionLabel")
        self.gridLayout.addWidget(self.SectionLabel, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.NavGrid)
        NavWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(NavWindow)
        QtCore.QMetaObject.connectSlotsByName(NavWindow)

    def retranslateUi(self, NavWindow):
        _translate = QtCore.QCoreApplication.translate
        NavWindow.setWindowTitle(_translate("NavWindow", "Navigator"))
        self.ForwardButton.setText(_translate("NavWindow", ">>"))
        self.BackButton.setText(_translate("NavWindow", "<<"))
