# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preview_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PreviewWindow(object):
    def setupUi(self, PreviewWindow):
        PreviewWindow.setObjectName("PreviewWindow")
        PreviewWindow.resize(845, 538)
        self.centralwidget = QtWidgets.QWidget(PreviewWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.OptionsWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OptionsWidget.sizePolicy().hasHeightForWidth())
        self.OptionsWidget.setSizePolicy(sizePolicy)
        self.OptionsWidget.setObjectName("OptionsWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.OptionsWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.OptionsLayout = QtWidgets.QHBoxLayout()
        self.OptionsLayout.setSpacing(3)
        self.OptionsLayout.setObjectName("OptionsLayout")
        self.verticalLayout.addLayout(self.OptionsLayout)
        self.previewButton = QtWidgets.QPushButton(self.OptionsWidget)
        self.previewButton.setObjectName("previewButton")
        self.verticalLayout.addWidget(self.previewButton)
        self.ConfirmButtonBox = QtWidgets.QDialogButtonBox(self.OptionsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConfirmButtonBox.sizePolicy().hasHeightForWidth())
        self.ConfirmButtonBox.setSizePolicy(sizePolicy)
        self.ConfirmButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.ConfirmButtonBox.setCenterButtons(False)
        self.ConfirmButtonBox.setObjectName("ConfirmButtonBox")
        self.verticalLayout.addWidget(self.ConfirmButtonBox, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_2.addWidget(self.OptionsWidget, 0, QtCore.Qt.AlignVCenter)
        self.PreviewVerticalFrame = QtWidgets.QFrame(self.centralwidget)
        self.PreviewVerticalFrame.setObjectName("PreviewVerticalFrame")
        self.PreviewFrameLayout = QtWidgets.QVBoxLayout(self.PreviewVerticalFrame)
        self.PreviewFrameLayout.setObjectName("PreviewFrameLayout")
        self.PreviewLayout = QtWidgets.QHBoxLayout()
        self.PreviewLayout.setObjectName("PreviewLayout")
        self.PreviewFrameLayout.addLayout(self.PreviewLayout)
        self.horizontalLayout_2.addWidget(self.PreviewVerticalFrame)
        PreviewWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(PreviewWindow)
        QtCore.QMetaObject.connectSlotsByName(PreviewWindow)

    def retranslateUi(self, PreviewWindow):
        _translate = QtCore.QCoreApplication.translate
        PreviewWindow.setWindowTitle(_translate("PreviewWindow", "Preview Window"))
        self.previewButton.setText(_translate("PreviewWindow", "Preview"))
