# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'project_windowxsZULa.ui'
##
## Created by: Qt User Interface Compiler version 6.5.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QDockWidget, QHBoxLayout, QHeaderView,
    QMainWindow, QMenu, QMenuBar, QPlainTextEdit,
    QSizePolicy, QStatusBar, QTabWidget, QTableView,
    QTableWidget, QTableWidgetItem, QTreeWidget, QTreeWidgetItem,
    QVBoxLayout, QWidget)

class Ui_ProjectWindow(object):
    def setupUi(self, ProjectWindow):
        if not ProjectWindow.objectName():
            ProjectWindow.setObjectName(u"ProjectWindow")
        ProjectWindow.resize(1280, 800)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(ProjectWindow.sizePolicy().hasHeightForWidth())
        ProjectWindow.setSizePolicy(sizePolicy)
        ProjectWindow.setMinimumSize(QSize(0, 0))
        ProjectWindow.setBaseSize(QSize(1280, 800))
        ProjectWindow.setStyleSheet(u"")
        ProjectWindow.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.actionProjectNew = QAction(ProjectWindow)
        self.actionProjectNew.setObjectName(u"actionProjectNew")
        self.actionProjectOpen = QAction(ProjectWindow)
        self.actionProjectOpen.setObjectName(u"actionProjectOpen")
        self.actionProjectSave = QAction(ProjectWindow)
        self.actionProjectSave.setObjectName(u"actionProjectSave")
        self.actionImportGocad = QAction(ProjectWindow)
        self.actionImportGocad.setObjectName(u"actionImportGocad")
        self.actionExportCAD = QAction(ProjectWindow)
        self.actionExportCAD.setObjectName(u"actionExportCAD")
        self.actionQuit = QAction(ProjectWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionView3D = QAction(ProjectWindow)
        self.actionView3D.setObjectName(u"actionView3D")
        self.actionViewPlaneXsection = QAction(ProjectWindow)
        self.actionViewPlaneXsection.setObjectName(u"actionViewPlaneXsection")
        self.actionViewMap = QAction(ProjectWindow)
        self.actionViewMap.setObjectName(u"actionViewMap")
        self.actionViewXYPlot = QAction(ProjectWindow)
        self.actionViewXYPlot.setObjectName(u"actionViewXYPlot")
        self.actionAbout = QAction(ProjectWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionHelp = QAction(ProjectWindow)
        self.actionHelp.setObjectName(u"actionHelp")
        self.actionViewWellLog = QAction(ProjectWindow)
        self.actionViewWellLog.setObjectName(u"actionViewWellLog")
        self.actionViewStereoplot = QAction(ProjectWindow)
        self.actionViewStereoplot.setObjectName(u"actionViewStereoplot")
        self.actionViewHistogram = QAction(ProjectWindow)
        self.actionViewHistogram.setObjectName(u"actionViewHistogram")
        self.actionImportPyvista = QAction(ProjectWindow)
        self.actionImportPyvista.setObjectName(u"actionImportPyvista")
        self.actionImportVedo = QAction(ProjectWindow)
        self.actionImportVedo.setObjectName(u"actionImportVedo")
        self.actionImportDEM = QAction(ProjectWindow)
        self.actionImportDEM.setObjectName(u"actionImportDEM")
        self.actionImportOrthoImage = QAction(ProjectWindow)
        self.actionImportOrthoImage.setObjectName(u"actionImportOrthoImage")
        self.actionEditEntityRemove = QAction(ProjectWindow)
        self.actionEditEntityRemove.setObjectName(u"actionEditEntityRemove")
        self.actionEditTextureAdd = QAction(ProjectWindow)
        self.actionEditTextureAdd.setObjectName(u"actionEditTextureAdd")
        self.actionEditTextureRemove = QAction(ProjectWindow)
        self.actionEditTextureRemove.setObjectName(u"actionEditTextureRemove")
        self.actionEditEntityClone = QAction(ProjectWindow)
        self.actionEditEntityClone.setObjectName(u"actionEditEntityClone")
        self.actionImportGocadXsection = QAction(ProjectWindow)
        self.actionImportGocadXsection.setObjectName(u"actionImportGocadXsection")
        self.actionDelaunay2DInterpolation = QAction(ProjectWindow)
        self.actionDelaunay2DInterpolation.setObjectName(u"actionDelaunay2DInterpolation")
        self.actionDelaunay2DInterpolation.setCheckable(False)
        self.actionMergeEntities = QAction(ProjectWindow)
        self.actionMergeEntities.setObjectName(u"actionMergeEntities")
        self.actionPoissonInterpolation = QAction(ProjectWindow)
        self.actionPoissonInterpolation.setObjectName(u"actionPoissonInterpolation")
        self.actionSurfaceSmoothing = QAction(ProjectWindow)
        self.actionSurfaceSmoothing.setObjectName(u"actionSurfaceSmoothing")
        self.actionExtrusion = QAction(ProjectWindow)
        self.actionExtrusion.setObjectName(u"actionExtrusion")
        self.actionDecimationPro = QAction(ProjectWindow)
        self.actionDecimationPro.setObjectName(u"actionDecimationPro")
        self.actionSubdivisionResampling = QAction(ProjectWindow)
        self.actionSubdivisionResampling.setObjectName(u"actionSubdivisionResampling")
        self.actionDecimationQuadric = QAction(ProjectWindow)
        self.actionDecimationQuadric.setObjectName(u"actionDecimationQuadric")
        self.actionIntersectionXSection = QAction(ProjectWindow)
        self.actionIntersectionXSection.setObjectName(u"actionIntersectionXSection")
        self.actionProject2DEM = QAction(ProjectWindow)
        self.actionProject2DEM.setObjectName(u"actionProject2DEM")
        self.actionLoopStructuralImplicitModelling = QAction(ProjectWindow)
        self.actionLoopStructuralImplicitModelling.setObjectName(u"actionLoopStructuralImplicitModelling")
        self.actionImportSEGY = QAction(ProjectWindow)
        self.actionImportSEGY.setObjectName(u"actionImportSEGY")
        self.actionCalculateNormal = QAction(ProjectWindow)
        self.actionCalculateNormal.setObjectName(u"actionCalculateNormal")
        self.actionCalculateLineation = QAction(ProjectWindow)
        self.actionCalculateLineation.setObjectName(u"actionCalculateLineation")
        self.actionAddProperty = QAction(ProjectWindow)
        self.actionAddProperty.setObjectName(u"actionAddProperty")
        self.actionRemoveProperty = QAction(ProjectWindow)
        self.actionRemoveProperty.setObjectName(u"actionRemoveProperty")
        self.actionProject2XSection = QAction(ProjectWindow)
        self.actionProject2XSection.setObjectName(u"actionProject2XSection")
        self.actionImportSHP = QAction(ProjectWindow)
        self.actionImportSHP.setObjectName(u"actionImportSHP")
        self.actionImportGocadBoundary = QAction(ProjectWindow)
        self.actionImportGocadBoundary.setObjectName(u"actionImportGocadBoundary")
        self.actionImportXsectionImage = QAction(ProjectWindow)
        self.actionImportXsectionImage.setObjectName(u"actionImportXsectionImage")
        self.actionConnectedParts = QAction(ProjectWindow)
        self.actionConnectedParts.setObjectName(u"actionConnectedParts")
        self.actionSplitMultipart = QAction(ProjectWindow)
        self.actionSplitMultipart.setObjectName(u"actionSplitMultipart")
        self.actionImportPC = QAction(ProjectWindow)
        self.actionImportPC.setObjectName(u"actionImportPC")
        self.actionImportWellData = QAction(ProjectWindow)
        self.actionImportWellData.setObjectName(u"actionImportWellData")
        self.actionExportVTK = QAction(ProjectWindow)
        self.actionExportVTK.setObjectName(u"actionExportVTK")
        self.actionSplitSurf = QAction(ProjectWindow)
        self.actionSplitSurf.setObjectName(u"actionSplitSurf")
        self.actionRetopologize = QAction(ProjectWindow)
        self.actionRetopologize.setObjectName(u"actionRetopologize")
        self.actionBuildOctree = QAction(ProjectWindow)
        self.actionBuildOctree.setObjectName(u"actionBuildOctree")
        self.actionDecimatePointCloud = QAction(ProjectWindow)
        self.actionDecimatePointCloud.setObjectName(u"actionDecimatePointCloud")
        self.actionExportCSV = QAction(ProjectWindow)
        self.actionExportCSV.setObjectName(u"actionExportCSV")
        self.centralwidget = QWidget(ProjectWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QSize(0, 0))
        self.centralwidget.setBaseSize(QSize(638, 757))
        self.centralwidget.setStyleSheet(u"")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.tabCentral = QTabWidget(self.centralwidget)
        self.tabCentral.setObjectName(u"tabCentral")
        sizePolicy1 = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy1.setHorizontalStretch(1)
        sizePolicy1.setVerticalStretch(1)
        sizePolicy1.setHeightForWidth(self.tabCentral.sizePolicy().hasHeightForWidth())
        self.tabCentral.setSizePolicy(sizePolicy1)
        self.tabCentral.setMinimumSize(QSize(0, 0))
        self.tabCentral.setBaseSize(QSize(0, 0))
        self.tabGeology = QWidget()
        self.tabGeology.setObjectName(u"tabGeology")
        sizePolicy1.setHeightForWidth(self.tabGeology.sizePolicy().hasHeightForWidth())
        self.tabGeology.setSizePolicy(sizePolicy1)
        self.tabGeology.setMinimumSize(QSize(0, 0))
        self.tabGeology.setBaseSize(QSize(0, 0))
        self.horizontalLayout = QHBoxLayout(self.tabGeology)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.GeologyTableView = QTableView(self.tabGeology)
        self.GeologyTableView.setObjectName(u"GeologyTableView")
        sizePolicy1.setHeightForWidth(self.GeologyTableView.sizePolicy().hasHeightForWidth())
        self.GeologyTableView.setSizePolicy(sizePolicy1)
        self.GeologyTableView.setMinimumSize(QSize(0, 0))
        self.GeologyTableView.setBaseSize(QSize(0, 0))
        self.GeologyTableView.setSortingEnabled(True)

        self.horizontalLayout.addWidget(self.GeologyTableView)

        self.tabCentral.addTab(self.tabGeology, "")
        self.tabXSections = QWidget()
        self.tabXSections.setObjectName(u"tabXSections")
        sizePolicy1.setHeightForWidth(self.tabXSections.sizePolicy().hasHeightForWidth())
        self.tabXSections.setSizePolicy(sizePolicy1)
        self.horizontalLayout_3 = QHBoxLayout(self.tabXSections)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.XSectionsTableView = QTableView(self.tabXSections)
        self.XSectionsTableView.setObjectName(u"XSectionsTableView")
        sizePolicy1.setHeightForWidth(self.XSectionsTableView.sizePolicy().hasHeightForWidth())
        self.XSectionsTableView.setSizePolicy(sizePolicy1)
        self.XSectionsTableView.setSortingEnabled(True)

        self.horizontalLayout_3.addWidget(self.XSectionsTableView)

        self.tabCentral.addTab(self.tabXSections, "")
        self.tabBoundaries = QWidget()
        self.tabBoundaries.setObjectName(u"tabBoundaries")
        sizePolicy1.setHeightForWidth(self.tabBoundaries.sizePolicy().hasHeightForWidth())
        self.tabBoundaries.setSizePolicy(sizePolicy1)
        self.horizontalLayout_4 = QHBoxLayout(self.tabBoundaries)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.BoundariesTableView = QTableView(self.tabBoundaries)
        self.BoundariesTableView.setObjectName(u"BoundariesTableView")
        sizePolicy1.setHeightForWidth(self.BoundariesTableView.sizePolicy().hasHeightForWidth())
        self.BoundariesTableView.setSizePolicy(sizePolicy1)
        self.BoundariesTableView.setSortingEnabled(True)

        self.horizontalLayout_4.addWidget(self.BoundariesTableView)

        self.tabCentral.addTab(self.tabBoundaries, "")
        self.tabMeshes3D = QWidget()
        self.tabMeshes3D.setObjectName(u"tabMeshes3D")
        sizePolicy1.setHeightForWidth(self.tabMeshes3D.sizePolicy().hasHeightForWidth())
        self.tabMeshes3D.setSizePolicy(sizePolicy1)
        self.horizontalLayout_5 = QHBoxLayout(self.tabMeshes3D)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.Meshes3DTableView = QTableView(self.tabMeshes3D)
        self.Meshes3DTableView.setObjectName(u"Meshes3DTableView")
        sizePolicy1.setHeightForWidth(self.Meshes3DTableView.sizePolicy().hasHeightForWidth())
        self.Meshes3DTableView.setSizePolicy(sizePolicy1)
        self.Meshes3DTableView.setSortingEnabled(True)

        self.horizontalLayout_5.addWidget(self.Meshes3DTableView)

        self.tabCentral.addTab(self.tabMeshes3D, "")
        self.tabDOMs = QWidget()
        self.tabDOMs.setObjectName(u"tabDOMs")
        sizePolicy1.setHeightForWidth(self.tabDOMs.sizePolicy().hasHeightForWidth())
        self.tabDOMs.setSizePolicy(sizePolicy1)
        self.horizontalLayout_6 = QHBoxLayout(self.tabDOMs)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.DOMsTableView = QTableView(self.tabDOMs)
        self.DOMsTableView.setObjectName(u"DOMsTableView")
        sizePolicy1.setHeightForWidth(self.DOMsTableView.sizePolicy().hasHeightForWidth())
        self.DOMsTableView.setSizePolicy(sizePolicy1)
        self.DOMsTableView.setSortingEnabled(True)

        self.horizontalLayout_6.addWidget(self.DOMsTableView)

        self.tabCentral.addTab(self.tabDOMs, "")
        self.tabImages = QWidget()
        self.tabImages.setObjectName(u"tabImages")
        sizePolicy1.setHeightForWidth(self.tabImages.sizePolicy().hasHeightForWidth())
        self.tabImages.setSizePolicy(sizePolicy1)
        self.horizontalLayout_7 = QHBoxLayout(self.tabImages)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.ImagesTableView = QTableView(self.tabImages)
        self.ImagesTableView.setObjectName(u"ImagesTableView")
        sizePolicy1.setHeightForWidth(self.ImagesTableView.sizePolicy().hasHeightForWidth())
        self.ImagesTableView.setSizePolicy(sizePolicy1)
        self.ImagesTableView.setSortingEnabled(True)

        self.horizontalLayout_7.addWidget(self.ImagesTableView)

        self.tabCentral.addTab(self.tabImages, "")
        self.tabWells = QWidget()
        self.tabWells.setObjectName(u"tabWells")
        sizePolicy1.setHeightForWidth(self.tabWells.sizePolicy().hasHeightForWidth())
        self.tabWells.setSizePolicy(sizePolicy1)
        self.horizontalLayout_8 = QHBoxLayout(self.tabWells)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.WellsTableView = QTableView(self.tabWells)
        self.WellsTableView.setObjectName(u"WellsTableView")
        sizePolicy1.setHeightForWidth(self.WellsTableView.sizePolicy().hasHeightForWidth())
        self.WellsTableView.setSizePolicy(sizePolicy1)
        self.WellsTableView.setMinimumSize(QSize(0, 0))

        self.horizontalLayout_8.addWidget(self.WellsTableView)

        self.tabCentral.addTab(self.tabWells, "")
        self.tabFluids = QWidget()
        self.tabFluids.setObjectName(u"tabFluids")
        self.tabFluids.setEnabled(True)
        sizePolicy2 = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.tabFluids.sizePolicy().hasHeightForWidth())
        self.tabFluids.setSizePolicy(sizePolicy2)
        self.tabFluids.setMinimumSize(QSize(1, 1))
        self.tabFluids.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.horizontalLayout_9 = QHBoxLayout(self.tabFluids)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.FluidsTableView = QTableView(self.tabFluids)
        self.FluidsTableView.setObjectName(u"FluidsTableView")
        sizePolicy1.setHeightForWidth(self.FluidsTableView.sizePolicy().hasHeightForWidth())
        self.FluidsTableView.setSizePolicy(sizePolicy1)

        self.horizontalLayout_9.addWidget(self.FluidsTableView)

        self.tabCentral.addTab(self.tabFluids, "")
        self.tabBackgrounds = QWidget()
        self.tabBackgrounds.setObjectName(u"tabBackgrounds")
        sizePolicy1.setHeightForWidth(self.tabBackgrounds.sizePolicy().hasHeightForWidth())
        self.tabBackgrounds.setSizePolicy(sizePolicy1)
        self.horizontalLayout_10 = QHBoxLayout(self.tabBackgrounds)
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.BackgroundsTableView = QTableView(self.tabBackgrounds)
        self.BackgroundsTableView.setObjectName(u"BackgroundsTableView")
        sizePolicy1.setHeightForWidth(self.BackgroundsTableView.sizePolicy().hasHeightForWidth())
        self.BackgroundsTableView.setSizePolicy(sizePolicy1)

        self.horizontalLayout_10.addWidget(self.BackgroundsTableView)

        self.tabCentral.addTab(self.tabBackgrounds, "")
        self.tabLegend = QWidget()
        self.tabLegend.setObjectName(u"tabLegend")
        sizePolicy1.setHeightForWidth(self.tabLegend.sizePolicy().hasHeightForWidth())
        self.tabLegend.setSizePolicy(sizePolicy1)
        self.tabLegend.setMinimumSize(QSize(0, 0))
        self.tabLegend.setBaseSize(QSize(0, 0))
        self.horizontalLayout_11 = QHBoxLayout(self.tabLegend)
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.LegendTreeWidget = QTreeWidget(self.tabLegend)
        __qtreewidgetitem = QTreeWidgetItem()
        __qtreewidgetitem.setText(0, u"1");
        self.LegendTreeWidget.setHeaderItem(__qtreewidgetitem)
        self.LegendTreeWidget.setObjectName(u"LegendTreeWidget")
        sizePolicy1.setHeightForWidth(self.LegendTreeWidget.sizePolicy().hasHeightForWidth())
        self.LegendTreeWidget.setSizePolicy(sizePolicy1)
        self.LegendTreeWidget.setMinimumSize(QSize(0, 0))
        self.LegendTreeWidget.setBaseSize(QSize(0, 0))

        self.horizontalLayout_11.addWidget(self.LegendTreeWidget)

        self.tabCentral.addTab(self.tabLegend, "")
        self.tabProperties = QWidget()
        self.tabProperties.setObjectName(u"tabProperties")
        sizePolicy1.setHeightForWidth(self.tabProperties.sizePolicy().hasHeightForWidth())
        self.tabProperties.setSizePolicy(sizePolicy1)
        self.tabProperties.setMinimumSize(QSize(0, 0))
        self.tabProperties.setBaseSize(QSize(0, 0))
        self.tabProperties.setToolTipDuration(-3)
        self.horizontalLayout_12 = QHBoxLayout(self.tabProperties)
        self.horizontalLayout_12.setObjectName(u"horizontalLayout_12")
        self.PropertiesTableWidget = QTableWidget(self.tabProperties)
        self.PropertiesTableWidget.setObjectName(u"PropertiesTableWidget")
        sizePolicy1.setHeightForWidth(self.PropertiesTableWidget.sizePolicy().hasHeightForWidth())
        self.PropertiesTableWidget.setSizePolicy(sizePolicy1)
        self.PropertiesTableWidget.setMinimumSize(QSize(0, 0))
        self.PropertiesTableWidget.setBaseSize(QSize(0, 0))

        self.horizontalLayout_12.addWidget(self.PropertiesTableWidget)

        self.tabCentral.addTab(self.tabProperties, "")
        self.tabTerminal = QWidget()
        self.tabTerminal.setObjectName(u"tabTerminal")
        sizePolicy1.setHeightForWidth(self.tabTerminal.sizePolicy().hasHeightForWidth())
        self.tabTerminal.setSizePolicy(sizePolicy1)
        self.tabTerminal.setMinimumSize(QSize(0, 0))
        self.tabTerminal.setBaseSize(QSize(0, 0))
        self.horizontalLayout_13 = QHBoxLayout(self.tabTerminal)
        self.horizontalLayout_13.setObjectName(u"horizontalLayout_13")
        self.TextTerminal = QPlainTextEdit(self.tabTerminal)
        self.TextTerminal.setObjectName(u"TextTerminal")
        sizePolicy1.setHeightForWidth(self.TextTerminal.sizePolicy().hasHeightForWidth())
        self.TextTerminal.setSizePolicy(sizePolicy1)
        self.TextTerminal.setMinimumSize(QSize(0, 0))
        self.TextTerminal.setBaseSize(QSize(0, 0))
        self.TextTerminal.setReadOnly(True)

        self.horizontalLayout_13.addWidget(self.TextTerminal)

        self.tabCentral.addTab(self.tabTerminal, "")

        self.verticalLayout.addWidget(self.tabCentral)

        ProjectWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(ProjectWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1280, 22))
        sizePolicy3 = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Minimum)
        sizePolicy3.setHorizontalStretch(1)
        sizePolicy3.setVerticalStretch(1)
        sizePolicy3.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy3)
        self.menubar.setMinimumSize(QSize(0, 22))
        self.menubar.setMaximumSize(QSize(16777215, 16777215))
        self.menubar.setBaseSize(QSize(0, 0))
        font = QFont()
        font.setFamilies([u"MS Shell Dlg 2"])
        font.setPointSize(9)
        font.setBold(True)
        self.menubar.setFont(font)
        self.menubar.setAutoFillBackground(False)
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuFile.setTearOffEnabled(True)
        self.menuWindow = QMenu(self.menubar)
        self.menuWindow.setObjectName(u"menuWindow")
        self.menuWindow.setTearOffEnabled(True)
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuHelp.setTearOffEnabled(True)
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        sizePolicy2.setHeightForWidth(self.menuEdit.sizePolicy().hasHeightForWidth())
        self.menuEdit.setSizePolicy(sizePolicy2)
        self.menuEdit.setTearOffEnabled(True)
        self.menuInterpolation_tools = QMenu(self.menubar)
        self.menuInterpolation_tools.setObjectName(u"menuInterpolation_tools")
        self.menuInterpolation_tools.setTearOffEnabled(True)
        ProjectWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(ProjectWindow)
        self.statusbar.setObjectName(u"statusbar")
        sizePolicy4 = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy4)
        ProjectWindow.setStatusBar(self.statusbar)
        self.dockWidget = QDockWidget(ProjectWindow)
        self.dockWidget.setObjectName(u"dockWidget")
        self.dockWidget.setMinimumSize(QSize(80, 40))
        self.dockWidget.setMaximumSize(QSize(524287, 524287))
        self.dockWidget.setBaseSize(QSize(638, 757))
        self.dockWidget.setFeatures(QDockWidget.DockWidgetClosable|QDockWidget.DockWidgetFloatable|QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(Qt.RightDockWidgetArea)
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        sizePolicy2.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy2)
        self.dockWidget.setWidget(self.dockWidgetContents)
        ProjectWindow.addDockWidget(Qt.RightDockWidgetArea, self.dockWidget)

        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuInterpolation_tools.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menuFile.addAction(self.actionProjectNew)
        self.menuFile.addAction(self.actionProjectOpen)
        self.menuFile.addAction(self.actionProjectSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionImportGocad)
        self.menuFile.addAction(self.actionImportGocadXsection)
        self.menuFile.addAction(self.actionImportGocadBoundary)
        self.menuFile.addAction(self.actionImportPC)
        self.menuFile.addAction(self.actionImportPyvista)
        self.menuFile.addAction(self.actionImportVedo)
        self.menuFile.addAction(self.actionImportSHP)
        self.menuFile.addAction(self.actionImportDEM)
        self.menuFile.addAction(self.actionImportOrthoImage)
        self.menuFile.addAction(self.actionImportXsectionImage)
        self.menuFile.addAction(self.actionImportWellData)
        self.menuFile.addAction(self.actionImportSEGY)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExportCAD)
        self.menuFile.addAction(self.actionExportVTK)
        self.menuFile.addAction(self.actionExportCSV)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuWindow.addAction(self.actionView3D)
        self.menuWindow.addAction(self.actionViewMap)
        self.menuWindow.addAction(self.actionViewPlaneXsection)
        self.menuWindow.addAction(self.actionViewWellLog)
        self.menuWindow.addSeparator()
        self.menuWindow.addAction(self.actionViewXYPlot)
        self.menuWindow.addAction(self.actionViewHistogram)
        self.menuWindow.addAction(self.actionViewStereoplot)
        self.menuWindow.addSeparator()
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menuEdit.addAction(self.actionEditEntityClone)
        self.menuEdit.addAction(self.actionEditEntityRemove)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionConnectedParts)
        self.menuEdit.addAction(self.actionMergeEntities)
        self.menuEdit.addAction(self.actionSplitMultipart)
        self.menuEdit.addAction(self.actionDecimatePointCloud)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionEditTextureAdd)
        self.menuEdit.addAction(self.actionEditTextureRemove)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionAddProperty)
        self.menuEdit.addAction(self.actionRemoveProperty)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCalculateNormal)
        self.menuEdit.addAction(self.actionCalculateLineation)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionBuildOctree)
        self.menuInterpolation_tools.addAction(self.actionDelaunay2DInterpolation)
        self.menuInterpolation_tools.addAction(self.actionPoissonInterpolation)
        self.menuInterpolation_tools.addAction(self.actionLoopStructuralImplicitModelling)
        self.menuInterpolation_tools.addSeparator()
        self.menuInterpolation_tools.addAction(self.actionSurfaceSmoothing)
        self.menuInterpolation_tools.addAction(self.actionSubdivisionResampling)
        self.menuInterpolation_tools.addAction(self.actionDecimationPro)
        self.menuInterpolation_tools.addAction(self.actionDecimationQuadric)
        self.menuInterpolation_tools.addAction(self.actionRetopologize)
        self.menuInterpolation_tools.addSeparator()
        self.menuInterpolation_tools.addAction(self.actionExtrusion)
        self.menuInterpolation_tools.addAction(self.actionIntersectionXSection)
        self.menuInterpolation_tools.addAction(self.actionProject2XSection)
        self.menuInterpolation_tools.addAction(self.actionProject2DEM)
        self.menuInterpolation_tools.addAction(self.actionSplitSurf)

        self.retranslateUi(ProjectWindow)

        self.tabCentral.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(ProjectWindow)
    # setupUi

    def retranslateUi(self, ProjectWindow):
        ProjectWindow.setWindowTitle(QCoreApplication.translate("ProjectWindow", u"PZero", None))
        self.actionProjectNew.setText(QCoreApplication.translate("ProjectWindow", u"New Project", None))
        self.actionProjectOpen.setText(QCoreApplication.translate("ProjectWindow", u"Open Project", None))
        self.actionProjectSave.setText(QCoreApplication.translate("ProjectWindow", u"Save Project", None))
        self.actionImportGocad.setText(QCoreApplication.translate("ProjectWindow", u"Import Gocad", None))
#if QT_CONFIG(tooltip)
        self.actionImportGocad.setToolTip(QCoreApplication.translate("ProjectWindow", u"Import Gocad", None))
#endif // QT_CONFIG(tooltip)
        self.actionExportCAD.setText(QCoreApplication.translate("ProjectWindow", u"Export CAD", None))
        self.actionQuit.setText(QCoreApplication.translate("ProjectWindow", u"Quit", None))
        self.actionView3D.setText(QCoreApplication.translate("ProjectWindow", u"3D View", None))
        self.actionViewPlaneXsection.setText(QCoreApplication.translate("ProjectWindow", u"Plane X Section View", None))
        self.actionViewMap.setText(QCoreApplication.translate("ProjectWindow", u"Map View", None))
        self.actionViewXYPlot.setText(QCoreApplication.translate("ProjectWindow", u"XY Plot View", None))
        self.actionAbout.setText(QCoreApplication.translate("ProjectWindow", u"About", None))
        self.actionHelp.setText(QCoreApplication.translate("ProjectWindow", u"Help", None))
        self.actionViewWellLog.setText(QCoreApplication.translate("ProjectWindow", u"Well Log View", None))
        self.actionViewStereoplot.setText(QCoreApplication.translate("ProjectWindow", u"Stereoplot View", None))
        self.actionViewHistogram.setText(QCoreApplication.translate("ProjectWindow", u"Histogram View", None))
        self.actionImportPyvista.setText(QCoreApplication.translate("ProjectWindow", u"Import PyVista", None))
        self.actionImportVedo.setText(QCoreApplication.translate("ProjectWindow", u"Import Vedo", None))
        self.actionImportDEM.setText(QCoreApplication.translate("ProjectWindow", u"Import DEM", None))
        self.actionImportOrthoImage.setText(QCoreApplication.translate("ProjectWindow", u"Import OrthoImage", None))
        self.actionEditEntityRemove.setText(QCoreApplication.translate("ProjectWindow", u"Remove Entity", None))
        self.actionEditTextureAdd.setText(QCoreApplication.translate("ProjectWindow", u"Add Texture", None))
        self.actionEditTextureRemove.setText(QCoreApplication.translate("ProjectWindow", u"Remove Texture", None))
        self.actionEditEntityClone.setText(QCoreApplication.translate("ProjectWindow", u"Clone Entity", None))
        self.actionImportGocadXsection.setText(QCoreApplication.translate("ProjectWindow", u"Import Gocad Xsection", None))
        self.actionDelaunay2DInterpolation.setText(QCoreApplication.translate("ProjectWindow", u"Delaunay 2D", None))
        self.actionMergeEntities.setText(QCoreApplication.translate("ProjectWindow", u"Merge Entities", None))
        self.actionPoissonInterpolation.setText(QCoreApplication.translate("ProjectWindow", u"Poisson", None))
        self.actionSurfaceSmoothing.setText(QCoreApplication.translate("ProjectWindow", u"Surface Smoothing", None))
        self.actionExtrusion.setText(QCoreApplication.translate("ProjectWindow", u"Extrusion", None))
        self.actionDecimationPro.setText(QCoreApplication.translate("ProjectWindow", u"Decimation Pro", None))
#if QT_CONFIG(tooltip)
        self.actionDecimationPro.setToolTip(QCoreApplication.translate("ProjectWindow", u"DecimationPro", None))
#endif // QT_CONFIG(tooltip)
        self.actionSubdivisionResampling.setText(QCoreApplication.translate("ProjectWindow", u"Subdivision Resampling", None))
        self.actionDecimationQuadric.setText(QCoreApplication.translate("ProjectWindow", u"Decimation Quadric", None))
#if QT_CONFIG(tooltip)
        self.actionDecimationQuadric.setToolTip(QCoreApplication.translate("ProjectWindow", u"DecimationQuadric", None))
#endif // QT_CONFIG(tooltip)
        self.actionIntersectionXSection.setText(QCoreApplication.translate("ProjectWindow", u"XSection Intersection", None))
        self.actionProject2DEM.setText(QCoreApplication.translate("ProjectWindow", u"Project to DEM", None))
        self.actionLoopStructuralImplicitModelling.setText(QCoreApplication.translate("ProjectWindow", u"LoopStructural Implicit Modelling", None))
        self.actionImportSEGY.setText(QCoreApplication.translate("ProjectWindow", u"Import SEGY", None))
        self.actionCalculateNormal.setText(QCoreApplication.translate("ProjectWindow", u"Calculate normal", None))
#if QT_CONFIG(tooltip)
        self.actionCalculateNormal.setToolTip(QCoreApplication.translate("ProjectWindow", u"Calculate normal unit vector", None))
#endif // QT_CONFIG(tooltip)
        self.actionCalculateLineation.setText(QCoreApplication.translate("ProjectWindow", u"Calculate lineation", None))
#if QT_CONFIG(tooltip)
        self.actionCalculateLineation.setToolTip(QCoreApplication.translate("ProjectWindow", u"Calculate lineation unit vector", None))
#endif // QT_CONFIG(tooltip)
        self.actionAddProperty.setText(QCoreApplication.translate("ProjectWindow", u"Add property", None))
#if QT_CONFIG(tooltip)
        self.actionAddProperty.setToolTip(QCoreApplication.translate("ProjectWindow", u"Add empty property", None))
#endif // QT_CONFIG(tooltip)
        self.actionRemoveProperty.setText(QCoreApplication.translate("ProjectWindow", u"Remove property", None))
        self.actionProject2XSection.setText(QCoreApplication.translate("ProjectWindow", u"Project to XSection", None))
        self.actionImportSHP.setText(QCoreApplication.translate("ProjectWindow", u"Import SHP", None))
        self.actionImportGocadBoundary.setText(QCoreApplication.translate("ProjectWindow", u"Import Gocad Boundary", None))
        self.actionImportXsectionImage.setText(QCoreApplication.translate("ProjectWindow", u"Import Xsection Image", None))
        self.actionConnectedParts.setText(QCoreApplication.translate("ProjectWindow", u"Connected Parts", None))
        self.actionSplitMultipart.setText(QCoreApplication.translate("ProjectWindow", u"Split Multi-part", None))
        self.actionImportPC.setText(QCoreApplication.translate("ProjectWindow", u"Import Point Clouds", None))
        self.actionImportWellData.setText(QCoreApplication.translate("ProjectWindow", u"Import well data", None))
        self.actionExportVTK.setText(QCoreApplication.translate("ProjectWindow", u"Export vtk", None))
        self.actionSplitSurf.setText(QCoreApplication.translate("ProjectWindow", u"Split surfaces", None))
        self.actionRetopologize.setText(QCoreApplication.translate("ProjectWindow", u"Retopologize", None))
        self.actionBuildOctree.setText(QCoreApplication.translate("ProjectWindow", u"Build octree", None))
        self.actionDecimatePointCloud.setText(QCoreApplication.translate("ProjectWindow", u"Decimate point cloud", None))
        self.actionExportCSV.setText(QCoreApplication.translate("ProjectWindow", u"Export CSV", None))
#if QT_CONFIG(tooltip)
        self.tabGeology.setToolTip(QCoreApplication.translate("ProjectWindow", u"Entities", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(accessibility)
        self.tabGeology.setAccessibleName(QCoreApplication.translate("ProjectWindow", u"Entities", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(tooltip)
        self.GeologyTableView.setToolTip(QCoreApplication.translate("ProjectWindow", u"Entities", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(accessibility)
        self.GeologyTableView.setAccessibleName(QCoreApplication.translate("ProjectWindow", u"Entities", None))
#endif // QT_CONFIG(accessibility)
        self.tabCentral.setTabText(self.tabCentral.indexOf(self.tabGeology), QCoreApplication.translate("ProjectWindow", u"Geology", None))
#if QT_CONFIG(tooltip)
        self.tabCentral.setTabToolTip(self.tabCentral.indexOf(self.tabGeology), QCoreApplication.translate("ProjectWindow", u"Geology", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.tabCentral.setTabWhatsThis(self.tabCentral.indexOf(self.tabGeology), QCoreApplication.translate("ProjectWindow", u"Geology", None))
#endif // QT_CONFIG(whatsthis)
        self.tabCentral.setTabText(self.tabCentral.indexOf(self.tabXSections), QCoreApplication.translate("ProjectWindow", u"X Sections", None))
#if QT_CONFIG(tooltip)
        self.tabCentral.setTabToolTip(self.tabCentral.indexOf(self.tabXSections), QCoreApplication.translate("ProjectWindow", u"X Sections", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.tabCentral.setTabWhatsThis(self.tabCentral.indexOf(self.tabXSections), QCoreApplication.translate("ProjectWindow", u"X Sections", None))
#endif // QT_CONFIG(whatsthis)
        self.tabCentral.setTabText(self.tabCentral.indexOf(self.tabBoundaries), QCoreApplication.translate("ProjectWindow", u"Boundaries", None))
        self.tabCentral.setTabText(self.tabCentral.indexOf(self.tabMeshes3D), QCoreApplication.translate("ProjectWindow", u"3D Meshes and Grids", None))
#if QT_CONFIG(tooltip)
        self.tabCentral.setTabToolTip(self.tabCentral.indexOf(self.tabMeshes3D), QCoreApplication.translate("ProjectWindow", u"3D Meshes and Grids", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.tabCentral.setTabWhatsThis(self.tabCentral.indexOf(self.tabMeshes3D), QCoreApplication.translate("ProjectWindow", u"3D Meshes and Grids", None))
#endif // QT_CONFIG(whatsthis)
        self.tabCentral.setTabText(self.tabCentral.indexOf(self.tabDOMs), QCoreApplication.translate("ProjectWindow", u"DEMs and DOMs", None))
#if QT_CONFIG(tooltip)
        self.tabCentral.setTabToolTip(self.tabCentral.indexOf(self.tabDOMs), QCoreApplication.translate("ProjectWindow", u"DEMs and DOMs", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.tabCentral.setTabWhatsThis(self.tabCentral.indexOf(self.tabDOMs), QCoreApplication.translate("ProjectWindow", u"DEMs and DOMs", None))
#endif // QT_CONFIG(whatsthis)
        self.tabCentral.setTabText(self.tabCentral.indexOf(self.tabImages), QCoreApplication.translate("ProjectWindow", u"Images", None))
#if QT_CONFIG(tooltip)
        self.tabCentral.setTabToolTip(self.tabCentral.indexOf(self.tabImages), QCoreApplication.translate("ProjectWindow", u"Images", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.tabCentral.setTabWhatsThis(self.tabCentral.indexOf(self.tabImages), QCoreApplication.translate("ProjectWindow", u"Images", None))
#endif // QT_CONFIG(whatsthis)
        self.tabCentral.setTabText(self.tabCentral.indexOf(self.tabWells), QCoreApplication.translate("ProjectWindow", u"Wells", None))
        self.tabCentral.setTabText(self.tabCentral.indexOf(self.tabFluids), QCoreApplication.translate("ProjectWindow", u"Fluid contacts", None))
        self.tabCentral.setTabText(self.tabCentral.indexOf(self.tabBackgrounds), QCoreApplication.translate("ProjectWindow", u"Background data", None))
#if QT_CONFIG(tooltip)
        self.tabLegend.setToolTip(QCoreApplication.translate("ProjectWindow", u"Legend", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(accessibility)
        self.tabLegend.setAccessibleName(QCoreApplication.translate("ProjectWindow", u"Legend", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(tooltip)
        self.LegendTreeWidget.setToolTip(QCoreApplication.translate("ProjectWindow", u"Legend", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(accessibility)
        self.LegendTreeWidget.setAccessibleName(QCoreApplication.translate("ProjectWindow", u"Legend", None))
#endif // QT_CONFIG(accessibility)
        self.tabCentral.setTabText(self.tabCentral.indexOf(self.tabLegend), QCoreApplication.translate("ProjectWindow", u"Legend", None))
#if QT_CONFIG(tooltip)
        self.tabProperties.setToolTip(QCoreApplication.translate("ProjectWindow", u"Properties", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(accessibility)
        self.tabProperties.setAccessibleName(QCoreApplication.translate("ProjectWindow", u"Properties", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(tooltip)
        self.PropertiesTableWidget.setToolTip(QCoreApplication.translate("ProjectWindow", u"Properties", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(accessibility)
        self.PropertiesTableWidget.setAccessibleName(QCoreApplication.translate("ProjectWindow", u"Properties", None))
#endif // QT_CONFIG(accessibility)
        self.tabCentral.setTabText(self.tabCentral.indexOf(self.tabProperties), QCoreApplication.translate("ProjectWindow", u"Properties", None))
#if QT_CONFIG(tooltip)
        self.tabTerminal.setToolTip(QCoreApplication.translate("ProjectWindow", u"Terminal", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(accessibility)
        self.tabTerminal.setAccessibleName(QCoreApplication.translate("ProjectWindow", u"Terminal", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(tooltip)
        self.TextTerminal.setToolTip(QCoreApplication.translate("ProjectWindow", u"Terminal", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(accessibility)
        self.TextTerminal.setAccessibleName(QCoreApplication.translate("ProjectWindow", u"Terminal", None))
#endif // QT_CONFIG(accessibility)
        self.tabCentral.setTabText(self.tabCentral.indexOf(self.tabTerminal), QCoreApplication.translate("ProjectWindow", u"Terminal", None))
#if QT_CONFIG(tooltip)
        self.tabCentral.setTabToolTip(self.tabCentral.indexOf(self.tabTerminal), QCoreApplication.translate("ProjectWindow", u"Terminal", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.tabCentral.setTabWhatsThis(self.tabCentral.indexOf(self.tabTerminal), QCoreApplication.translate("ProjectWindow", u"Terminal", None))
#endif // QT_CONFIG(whatsthis)
        self.menuFile.setTitle(QCoreApplication.translate("ProjectWindow", u"File", None))
        self.menuWindow.setTitle(QCoreApplication.translate("ProjectWindow", u"Window", None))
        self.menuHelp.setTitle(QCoreApplication.translate("ProjectWindow", u"Help", None))
        self.menuEdit.setTitle(QCoreApplication.translate("ProjectWindow", u"Edit", None))
        self.menuInterpolation_tools.setTitle(QCoreApplication.translate("ProjectWindow", u"Interpolation", None))
    # retranslateUi

