name: pzero
channels:
  - conda-forge
  - loop3d
  - defaults
dependencies:
  - python=3.8
  - blackd=23.7.0
  - cmocean=3.0.3
  - colorcet=3.0.1
  - ezdxf=1.0.3
  - geopandas=0.13.2
  - laspy=2.3.0
  - loopstructural=v1.5.11
  - lxml=4.9.2
  - mplstereonet=0.6.2
  - openpyxl=3.1.2
  - pyinstaller=5.13.0
  - pyqt=5.15.7
  - pytest=7.4.0
  - pythreejs=2.4.2
  - pyvistaqt=0.11.0
  - qtpy=2.3.1
  - rasterio=1.3.6
  - seaborn=0.12.2
  - shapely=1.8
  - sphinx=6.2.1
  - sphinx_rtd_theme=1.2.2
  - vedo=2023.4.6
  - vtk=9.2.6
  - xarray=2023.1.0
