name: CICD

on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4  # This should be first
      - name: Install dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies and run old_tests
        run: |
          pip install -r requirements.txt
          pip install pytest
          pytest

  release:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    outputs:
      version: ${{ steps.semantic.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN }}
      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@master
        id: semantic
        with:
          github_token: ${{ secrets.TOKEN }}

  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            arch: x86_64
          - os: macos-latest
            arch: arm64
          - os: ubuntu-latest
          - os: windows-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Build executable MacOS
        if: runner.os == 'macOS'
        run: |
          if [ "${{ matrix.arch }}" = "x86_64" ]; then
            # Install x86_64 Python using pyenv
            brew install pyenv
            PYTHON_CONFIGURE_OPTS="--with-universal-arch=x86_64" pyenv install 3.12.10
            pyenv global 3.12.10
            eval "$(pyenv init -)"
          fi
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          pyinstaller --onedir --windowed --target-arch ${{ matrix.arch }} --collect-all rasterio pzero.py --name pzero-${{ runner.os }}-${{ matrix.arch }}
        env:
          ARCHFLAGS: "-arch ${{ matrix.arch }}"
          CFLAGS: "-arch ${{ matrix.arch }}"
          LDFLAGS: "-arch ${{ matrix.arch }}"
      - name: Build executable Other
        if: runner.os != 'macOS'
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
          pyinstaller --onedir --windowed --collect-all rasterio pzero.py --name pzero-${{ runner.os }}
      - name: Zip executable (Unix/MacOS)
        if: runner.os != 'Windows'
        run: |
          cd dist
          if [ "${{ runner.os }}" = "macOS" ]; then
            zip -r pzero-${{ runner.os }}-${{ matrix.arch }}.zip pzero-${{ runner.os }}-${{ matrix.arch }}/*
          else
            zip -r pzero-${{ runner.os }}.zip pzero-${{ runner.os }}/*
          fi
        shell: bash
      - name: Zip executable (Windows)
        if: runner.os == 'Windows'
        run: |
          cd dist
          Compress-Archive -Path "pzero-${{ runner.os }}/*" -DestinationPath "pzero-${{ runner.os }}.zip"
        shell: pwsh
      - name: Upload executable
        run: |
          if [ "${{ runner.os }}" = "macOS" ]; then
            file="dist/pzero-${{ runner.os }}-${{ matrix.arch }}.zip"
          else
            file="dist/pzero-${{ runner.os }}.zip"
          fi
          gh release upload --clobber --repo $GITHUB_REPOSITORY v${{ needs.release.outputs.version }} "$file"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}